language: python
python:
- '3.5'

sudo: required
dist: xenial

install:
- sudo apt-get install texlive-xetex texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-context
- pip install "notebook==4.1" requests jupyter_cms jupyter_dashboards
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
- echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
- sudo apt-get install -y redis-server mongodb-org
addons:
  apt_packages:
  - pandoc
script:
  - ls /etc/init.d/
  - sudo service redis-server start
  - sudo mongo --version
  - sudo service mongodb start
  - bash tools/travis-deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: dc3e238ed4e4
  - COMMIT_AUTHOR_EMAIL: stefanos1316@gmail.com

